# -*- coding: utf-8 -*-
"""Viualization_and_Analysis_on_Restarent_data .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DNX2onPURyay8Z789Ko0nhNtmSlSATL7
"""

import seaborn as sns
import matplotlib.pyplot as plt

import pandas as pd
import numpy as np
data=pd.read_csv('/content/drive/MyDrive/Data.csv')

data.head()

data.groupby('Date')['Final Total'].mean().sort_values(ascending=False).head(1)

data['Invoice No.'].nunique()

m=data[data['Date']>='2023-09-01']

month=m[m['Date']<='2023-09-30']

month

month.groupby('Item Name')['Qty.'].sum().sort_values(ascending=False).head(1)

j=data[data['Date']>='2023-07-01']

july=data[data['Date']<='2023-07-31'].groupby('Category')['Qty.'].sum().sort_values(ascending=True).head(3)

sns.barplot(july)

p=data.groupby('Category')['Final Total'].sum()

plt.pie(p,labels=p.index)
plt.show()

